config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  # get '/' to: 'home#index'
  post 'data_input', to: 'home#data_input'
  post 'boton_input', to: 'home#boton_input'
  post 'boton_file', to: 'home#boton_file'
  get  'descargar_csv',  to: 'home#descargar_csv'
  get  'descargar_json', to: 'home#descargar_json'
  post 'importar_csv', to: 'home#importar_csv'

end

app/models/amount.rb
module Amount
    class Request
        include ActiveModel::Model

        URLS = {
            test: "url"
        }

        attr_accessor :apiKey, :monto

        def initialize(credentials = nil)
            return "Hola"
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  append_view_path "#{Rails.root}/app/views"
  require 'csv'
  require 'rest-client'

  def index
    if session[:formulario_monto] === nil
      inicial(500)
    else
      @data = session[:formulario_monto]
      @active_input = session[:input_activo]
      @active_input_file = session[:input_activo_file]
      @bsi = session[:bsi]
      @tabla = session[:array_tabla]
    end 
  end

  def inicial(monto) 
    data_estatic = [
      {
        moneda: "Bitcoin",
        interes_mensual: 5,
        balance_inicial: (monto).to_f
      },
      {
        moneda: "Ether",
        interes_mensual: 4.2,
        balance_inicial: (monto).to_f
      },
      {
        moneda: "Cardano",
        interes_mensual: 1,
        balance_inicial: (monto).to_f
      },     
    ]
    calcular_inversion(data_estatic)
  end

  def data_input
    data_estatic = [
      {
        moneda: "Bitcoin",
        interes_mensual: 5,
        balance_inicial: (params[:monto]).to_f
      },
      {
        moneda: "Ether",
        interes_mensual: 4.2,
        balance_inicial: (params[:monto]).to_f
      },
      {
        moneda: "Cardano",
        interes_mensual: 1,
        balance_inicial: (params[:monto]).to_f
      },      
    ]

    calcular_inversion(data_estatic)
  end

  def boton_input
    session[:input_activo] = 1
    session[:input_activo_file] = 0
    @active_input_file
    puts "holaaaa"
    redirect_to root_path
  end

  def boton_file
    session[:input_activo] = 0
    session[:input_activo_file] = 1
    redirect_to root_path
  end

  def descargar_csv
    @info=session[:formulario_monto]
    @active_input = session[:input_activo]
    respond_to do |format|
      format.json { render json: @info.to_json }
      format.xml { render xml: @info.to_xml }
      format.csv do
        response.headers['Content-Type'] = 'text/csv'
        response.headers['Content-Disposition'] = "attachment; filename=report-#{@active_input}.csv" 
        render csv: @info.to_json,  template: "csv/report"
      end
    end
  end


  def descargar_json
    @info=session[:formulario_monto]
    @active_input = session[:input_activo]
    respond_to do |format|
      # format.json { render json: @info.to_json }
      format.xml { render xml: @info.to_xml }
      format.json do
        response.headers['Content-Type'] = 'text/json'
        response.headers['Content-Disposition'] = "attachment; filename=report-#{@active_input}.json" 
        render json: @info.to_json,  template: "csv/report"
      end
    end
  end

  def importar_csv
    file_path = File.read(params[:file])
    cc= CSV.parse(file_path, headers: true)
    if cc[0].length === 3
    
      data=[]

      cc.each do |row|
        data.push({
          moneda: row["Moneda"],
          interes_mensual: row["Interes_mensual"],
          balance_inicial: row["balance_ini"]
        })
        # debugger
      end
      calcular_inversion(data)

    else
      redirect_to root_path, alert: "Error de documento, verifique la data los headers deben ser: Moneda, Interes_mensual, balance_ini (solo tres columnas) "
    end
  end

  def calcular_inversion(data_estatic)
    # reset_session
    # session.delete(:formulario_monto)
    session[:formulario_monto] =[]
    array_static = []
    array_tabla = []

    data_estatic.each do |d|
      case d[:moneda]
      when 'Bitcoin'
        puts "hola 1"
          response = soporte('BTC')
          montoResponse = response["rate"]
          array_tabla.push(response)
          
          puts montoResponse
      when 'Ether'
        puts "hola 2"
        response = soporte('ETH')
        montoResponse = response["rate"]
        array_tabla.push(response)
      when 'Cardano'
        puts "hola 3"
        response = soporte('ADA')
        montoResponse = response["rate"]
        array_tabla.push(response)
      else
        "Error en datos para calcular"
      end

        moneda= d[:moneda], #nombre de moneda  - dato
        montoInicial= d[:balance_inicial].to_f, #monto inicial  - dato
        porcentajeMensual=  d[:interes_mensual].to_f, #interes mensual - dato 

        porcentajeAnual= (porcentajeMensual/100)*12*100, # calculamos el porcentaje anual - calculo
        gananciaUSD= (porcentajeAnual/100)*montoInicial, # calculamos monto inicial por el porcentaje anual  obtenemos estimacion anual  - calculo
        estimacion= montoResponse*gananciaUSD, # multiplicamos ganancia anual por balance de moneda - calculo 
        response_monto = montoResponse #monto arrijado por la aplicacion segun el caso - dato        

      array_static.push(
        {
          moneda: d[:moneda],
          montoInicial: montoInicial,
          response_monto: response_monto,
          porcentajeMensual:porcentajeMensual,
          porcentajeAnual: porcentajeAnual,
          gananciaUSD: gananciaUSD,
          estimacion: estimacion,
        }
      )
    end
    # debugger
    session[:formulario_monto] = array_static
    session[:array_tabla] = array_tabla
    
    session[:input_activo] = 0
    session[:input_activo_file] = 0

    redirect_to root_path, alert: "Error de api, los datos retornados estaran a destiempo. Para valoracion de prueba se utilizara datos de soporte"
  end

  def coinApi(moneda) 
   response = RestClient.get("https://rest.coinapi.io/v1/exchangerate/#{moneda}/USD", 
    headers={
        'Accept' => "application/json",
        'Content-Type' =>"application/json",
        'X-CoinAPI-Key'=> "314EF134-05AC-4168-A3B6-FA46FB95BDFB"
    })
    rescue RestClient::TooManyRequests => e
      sleep(60)
      retry
    # end

    puts response.code
    return JSON.parse(response)
    # debugger
    # if response.code === 200
    #   return JSON.parse(response)
    # else      
    #   # session[:formulario_monto] = array_static
    #   redirect_to root_path, alert: "Error de api, los datos retornados estaran a destiempo"
    # end
    # session[:bsi] = json
  end

  def soporte(moneda)
    case moneda
    when 'BTC'
      response ={
        "time"=>"2024-02-02T03:40:25.0000000Z",
        "asset_id_base"=>"BTC",
        "asset_id_quote"=>"USD",
        "rate"=>43021.32
      }
      return response
    when 'ETH'
      response ={
        "time"=>"2024-02-02T03:40:25.0000000Z",
        "asset_id_base"=>"ETH",
        "asset_id_quote"=>"USD",
        "rate"=>2300.53
      }
      return response
    when 'ADA'
      response ={
        "time"=>"2024-02-02T03:40:25.0000000Z",
        "asset_id_base"=>"ADA",
        "asset_id_quote"=>"USD",
        "rate"=>0.51
      }
      return response
    else
      "Error en datos para calcular"
    end
  end

  # def coinApi_info_completa(moneda) 
  #   response = RestClient.get("https://rest.coinapi.io/v1/assets/#{moneda}", 
  #    headers={
  #        'Accept' => "application/json",
  #        'Content-Type' =>"application/json",
  #        'X-CoinAPI-Key'=> "1C25E9E3-33FB-40BD-8858-CF9459BE1C7A"
  #    })
  #    return JSON.parse(response)
  #    # session[:bsi] = json
  #  end


  private
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/csv/report.csv.erb
<% headers = ["Tipo_Moneda","Monto_invertido", "porcentaje_mensual", "porcentaje_anaul", "ganancia_USD", "Estimacion"] %> 
   
<%= CSV.generate_line headers %> 
<% @info.each do |f, i| %>
    <%= CSV.generate_line([f["moneda"], f["montoInicial"], f["porcentajeMensual"], f["porcentajeAnual"], f["gananciaUSD"], f["estimacion"]]) %>
<% end %>

app/views/home/_alert.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/home/_formout.html.erb
<% if @active_input === 1 %>
    <div class="container mt-5">
        <%= form_tag data_input_path, method: :post do %>
            <div class="col-12 col-sm-12 col-md-12 col-lg-12 mb-4">
                <%= number_field_tag :monto%>
                <%= submit_tag 'Calcular'%>
            </div>
        <% end %>
    </div>
<%end%>

<% if @active_input_file === 1 %>
    <div class="container mt-5">
        <%= form_tag importar_csv_path, multipart: true do %>
            <%= file_field_tag :file %>
            <%= submit_tag 'importar csv' %>
        <% end %>
    </div>
<%end%>

app/views/home/_table.html.erb
<div class=" container mt-5"> 
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Moneda base</th>
                <th scope="col">Moneda al cambio</th>
                <th scope="col">Taza</th>
            </tr>
        </thead>
        <tbody>
            <% @tabla.each do |f, i| %>
                <tr>
                    <th scope="row">
                        <i class='bx bx-star' ></i>
                    </th>
                    <td>
                        <div>
                        <% if f["asset_id_base"]  === "BTC" %>
                            <i class='bx bxl-bitcoin' style="font-size: 2rem;"></i> 
                                <strong>Bitcoin</strong>
                                <small><%= f["asset_id_base"] %></small>
                        <% end %>
                        <% if f["asset_id_base"]  === "ETH" %>
                            <i class='bx bxs-diamond' style="font-size: 2rem;"></i>
                                <strong>Ether</strong>
                                <small><%= f["asset_id_base"] %></small>
                        <% end %>
                        <% if f["asset_id_base"]  === "ADA" %>  
                            <i class='bx bx-loader' style="font-size: 2rem;"></i>  
                            <strong>Cardano</strong>
                            <small><%= f["asset_id_base"] %></small>
                        <% end %>
                           
                        </div>
                    </td>
                    <td><%= f["asset_id_quote"] %></td>
                    <td><%= f["rate"] %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/home/index.html.erb
<%= render "home/alert" %>
<%= render "home/formout" %>
<div class="container">
    <div class="d-flex flex-column flex-md-row p-4 gap-4 py-md-5 align-items-center justify-content-center">
        <% @data.each do |f, i| %>
            <div class="card col-4" data-bs-theme="light" style="width: 30vw;">
                <div class="card-header">
                    <h5 class="card-title text-center">
                        <% if f["moneda"]  === "Bitcoin" %>
                            <i class='bx bxl-bitcoin' style="font-size: 6rem;"></i> 
                        <% end %>
                        <% if f["moneda"]  === "Ether" %>
                            <i class='bx bxs-diamond' style="font-size: 6rem;"></i>
                        <% end %>
                        <% if f["moneda"]  === "Cardano" %>  
                            <i class='bx bx-loader' style="font-size: 6rem;"></i>  
                        <% end %>
                        <%= f["moneda"] %> 
                    </h5>
                    <h6 class="card-subtitle mb-2 text-body-secondary"></h6>
                </div> 
                <div class="card-body">    
                    <div class="row">
                        <div class="col-lg-5">
                            <ul class="list-unstyled d-flex flex-column gap-2">
                                <li>
                                    <a href="#" class="btn btn-hover-light rounded-2 d-flex align-items-start gap-2 py-2 px-3 lh-sm text-start">              
                                        <div>
                                            <strong>Monto invertido</strong>
                                            <small><%= f["montoInicial"]%></small>
                                        </div>
                                    </a>
                                </li>

                                <li>
                                    <a href="#" class="btn btn-hover-light rounded-2 d-flex align-items-start gap-2 py-2 px-3 lh-sm text-start">              
                                        <div>
                                            <strong>Monto Moneda</strong>
                                            <small><%= f["response_monto"]%></small>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        
                        <div class="d-none d-lg-block vr mx-4 opacity-5 p-0">&nbsp;</div>
                        <hr class="d-lg-none">

                        <div class="col-lg-auto pe-3">
                            <ul class="d-flex flex-column gap-2 list-unstyled small">
                                <li>
                                    <a href="#" class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">
                                        <div>
                                            <strong class="d-block">Ganancia Mensual</strong>
                                            <small><%= f["porcentajeMensual"]%> %</small>
                                        </div>
                                    </a>
                                </li>
                                <li class="mt-2">
                                    <a href="#" class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">
                                        <div>
                                            <strong class="d-block">Ganancia Anual</strong>
                                            <small><%= f["porcentajeAnual"]%> %</small>
                                        </div>
                                    </a>
                                </li>
                                <li class="mt-2">
                                    <a href="#" class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">
                                        <div>
                                            <strong class="d-block">Ganancia USD (Anual)</strong>
                                            <small><%= f["gananciaUSD"]%></small>
                                        </div>
                                    </a>
                                </li>
                                <li class="mt-2">
                                    <a href="#" class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover">
                                        <div>
                                            <strong class="d-block">Ganancia al cambio</strong>
                                            <small><%= f["estimacion"]%></small>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>   
                </div>
            </div>
        <% end %>        
    </div>
</div>

<div class=" container">
    <a class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover"> 
        <i class='bx bxs-file'></i>  <%= link_to 'csv', descargar_csv_path(format: :csv) %> 
    </a>
    <a class="link-offset-2 link-underline link-underline-opacity-25 link-underline-opacity-75-hover me-5"> 
        <%= link_to 'json', descargar_json_path(format: :json) %> <i class='bx bxs-file-json'></i> 
    </a>
</div>

<%= @bsi %>

<%= render "home/table" %>

app/views/layouts/_header.html.erb
<div class="container">
    <header class="p-3 text-bg-dark">
        <div class="container">
            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                    <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                </ul>

                <div class="text-end">
                    <button type="button" class="btn btn-outline-light me-2"><%= button_to "Calcular monto a invertir", boton_input_path, method: :post %></button>
                    
                    <button type="button" class="btn btn-warning"><%= button_to "Promedio desde csv", boton_file_path, method: :post %></button>
                </div>
            </div>
        </div>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PruebaDisrup6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
  </body>
</html>